### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by IgorRozani** [aspnet/Docs.pt-br#91]
The link "Contributing Guide", in the README, is broken. It redirects to the file CONTRIBUTING.md that doesn't exist.

![image](https://user-images.githubusercontent.com/802968/47242490-44239200-d3c5-11e8-8abc-0f938bf15ffa.png)

**Comment by CeciAc** [comment]
Hello, @IgorRozani 

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard @nokura  
please check this issue I think is related to the ones I assigned to you yesterday.
Also seems the same as the following:
https://github.com/MicrosoftDocs/IntuneDocs.pt-br/issues/22
https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9
https://github.com/PowerShell/powerShell-Docs.pt-br/issues/2

**Comment by JasonCard** [comment]
Hello @IgorRozani,

Thank you for letting us know.
We are working on localizing both README.md and CONTRIBUTING.md.
I will update when they are ready and this issue is resolved.

Kind regards,
Microsoft DOCS International Team

**Comment by strobelt** [comment]
Hi @JasonCard,

I would like to know if you want some help on translating the README and contribution guide to portuguese, as I would gladly help with this.

Thanks!

**Comment by JasonCard** [comment]
Hello @strobelt, 

Thank you very much for your offer to help, but translation for these files are already in progress and should be available soon. 

Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hello, @IgorRozani, @strobelt,

Thank you for your patience.
[README.md](https://github.com/aspnet/Docs.pt-br/blob/live/README.md) and [CONTRIBUTING.md](https://github.com/aspnet/Docs.pt-br/blob/live/CONTRIBUTING.md) are now localized in pt-br repo.

Kind regards,
Microsoft DOCS International Team
